import Adresa from "@/components/adresa";
import VypisAkci from "@/components/vypisAkci";
import Head from "next/head";
// import Image from "next/image";
// import Script from "next/script";
// import { getAllActions } from "../../lib/akceNahled";
// import Actions from "../components/actions";
import Carousel from "../components/carousel";
import Clanky from "../components/clanky";

// export async function getStaticProps() {
//   const allActions = await getAllActions();
//   return {
//     props: {
//       allActions: allActions,
//     },
//     revalidate: 10,
//   };
// }

export default function Home({ allActions }) {
  return (
    <>
      <Head>
        <title>Zodpovědný hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto bg-white">
        {/* {allPosts.nodes.map((post) => (
            <li key={post.id}>{post.title}</li>
          ))} */}
        <Carousel />
        <Clanky />
        <VypisAkci />
        <div className="max-w-6xl my-20 md:my-40 mx-auto">
          <Adresa />
        </div>
        {/* <Actions allActions={allActions} /> */}
      </div>
    </>
  );
}
