import Actions from "@/components/actions";
import Carousel from "@/components/carousel";
import Clanky from "@/components/clanky";
import Head from "next/head";
// import Image from "next/image";
import { getAllActions } from "../../lib/akceNahled";

export async function getStaticProps() {
  const allActions = await getAllActions();
  return {
    props: {
      allActions: allActions,
    },
    revalidate: 1,
  };
}

export default function Home({ allActions }) {
  return (
    <>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto bg-white">
        {/* {allPosts.nodes.map((post) => (
            <li key={post.id}>{post.title}</li>
          ))} */}
        <Carousel />
        <Clanky />
        <Actions allActions={allActions} />
      </div>
    </>
  );
}
